<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Link $block */
?>
<div class="link account" data-bind="scope: 'customer'">
    <a href="<?php echo $this->getUrl('customer/account'); ?>">
        <span class="account-icon"><?= $block->escapeHtml('Account') ?></span>
    </a>
</div>
